name: test
dependencies:
  - python=3.7.9
  - pip:
      - asgiref==3.2.10
      - dj-database-url==0.5.0
      - Django==2.2.12
      - django-heroku==0.3.1
      - gunicorn==20.0.4
      - Pillow==7.0.0
      - pipenv==2020.8.13
      - psycopg2==2.8.5
      - virtualenv==20.0.20
      - virtualenv-clone==0.5.4
      - whitenoise==4.1.4
