# Generated by Django 3.0.6 on 2020-09-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyID', models.AutoField(primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=40)),
                ('peopleInFaculty', models.IntegerField()),
                ('university', models.CharField(max_length=40)),
                ('queue', models.IntegerField()),
                ('requireMeanTime', models.FloatField()),
                ('timeStart', models.TimeField(null=True)),
                ('timeStop', models.TimeField(null=True)),
                ('timeExpect', models.TimeField()),
                ('status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('majorID', models.AutoField(primary_key=True, serialize=False)),
                ('majorName', models.CharField(max_length=40)),
                ('peopleInMajor', models.IntegerField(null=True)),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationDetail',
            fields=[
                ('detailID', models.AutoField(primary_key=True, serialize=False)),
                ('academinYear', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.BooleanField()),
                ('round', models.IntegerField()),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='CountRealTime',
            fields=[
                ('countID', models.AutoField(primary_key=True, serialize=False)),
                ('numOfCount', models.IntegerField()),
                ('detailID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GraduationDetail')),
            ],
        ),
    ]
