# Generated by Django 3.0.6 on 2020-09-05 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200905_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultynewlogic',
            name='peopleInFaculty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='facultynewlogic',
            name='queueFaculty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='facultynewlogic',
            name='requireMeanTime',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
