# Generated by Django 2.2.12 on 2020-09-06 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200906_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='peopleInFaculty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='queue',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='requireMeanTime',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='graduationdetail',
            name='academinYear',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='graduationdetail',
            name='round',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='graduationdetailnewlogic',
            name='academinYear',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='graduationdetailnewlogic',
            name='round',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='major',
            name='peopleInMajor',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='majornewlogic',
            name='numOfCount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='majornewlogic',
            name='peopleInMajor',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='majornewlogic',
            name='queueMajor',
            field=models.PositiveIntegerField(),
        ),
    ]
