# Generated by Django 2.2.12 on 2020-09-06 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200906_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='requireMeanTime',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facultynewlogic',
            name='requireMeanTime',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facultynewlogic',
            name='timeExpect',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
