# Generated by Django 2.2.12 on 2020-09-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200906_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultynewlogic',
            name='timeStart',
            field=models.TimeField(blank=True),
        ),
    ]
