# Generated by Django 3.0.6 on 2020-09-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyNewLogic',
            fields=[
                ('facultyID', models.AutoField(primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=40)),
                ('peopleInFaculty', models.IntegerField()),
                ('university', models.CharField(max_length=40)),
                ('queueFaculty', models.IntegerField()),
                ('requireMeanTime', models.FloatField()),
                ('timeStart', models.TimeField(null=True)),
                ('timeStop', models.TimeField(null=True)),
                ('timeExpect', models.TimeField()),
                ('speed', models.CharField(choices=[('Yes', 'OK'), ('No', 'NOT OK')], max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='graduationdetail',
            name='place',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='MajorNewLogic',
            fields=[
                ('majorID', models.AutoField(primary_key=True, serialize=False)),
                ('majorName', models.CharField(max_length=40)),
                ('peopleInMajor', models.IntegerField(null=True)),
                ('queueMajor', models.IntegerField()),
                ('numOfCount', models.IntegerField(null=True)),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationDetailNewLogic',
            fields=[
                ('detailID', models.AutoField(primary_key=True, serialize=False)),
                ('academinYear', models.IntegerField()),
                ('date', models.DateField()),
                ('typeCeremony', models.BooleanField()),
                ('round', models.IntegerField()),
                ('place', models.CharField(max_length=40, null=True)),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Faculty')),
            ],
        ),
    ]
