# Generated by Django 3.0.6 on 2020-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200905_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultynewlogic',
            name='speed',
            field=models.CharField(blank=True, choices=[('Yes', 'OK'), ('No', 'NOT OK')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='facultynewlogic',
            name='timeStart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultynewlogic',
            name='timeStop',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
