# Generated by Django 2.2.12 on 2020-09-06 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200905_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationdetailnewlogic',
            name='facultyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.FacultyNewLogic'),
        ),
        migrations.AlterField(
            model_name='majornewlogic',
            name='facultyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.FacultyNewLogic'),
        ),
    ]
