# Generated by Django 2.2.12 on 2020-09-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200906_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultynewlogic',
            name='speed',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='facultynewlogic',
            name='timeStart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
