# Generated by Django 2.2.12 on 2020-09-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_countrealtimenewlogic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrealtimenewlogic',
            name='detailID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GraduationDetailNewLogic'),
        ),
    ]
